### ISSUE TITLE
What is  'robustarch'

### ISSUE THREAD

**Issue by cod3r0k** [poloclub/robust-principles#1]
Hi, I have a problem in installation:

ModuleNotFoundError: No module named 'robustarch'

**Comment by ShengYun-Peng** [comment]
Hey @cod3r0k, thanks for your interest!

'robustarch' is the [package name](https://github.com/poloclub/robust-principles/blob/cf73dd0cf85de4cd4e0d06d113466b4dd763d028/setup.py#L5) for our robust principles. The package is installed for you [while creating the virtual environment](https://github.com/poloclub/robust-principles/blob/cf73dd0cf85de4cd4e0d06d113466b4dd763d028/Makefile#L28) with `make .venv_done`.
